### PR TITLE
Automatically search for model in dir for examples

### LINKED ISSUE #35: Could not run example: ERROR: Could not open 'deepspeech-0.8.0-models.tflite/output_graph.pb'
The [quickstart](https://docs.rs/crate/deepspeech/0.8.0) guide says to download the models from the [release announcement](https://github.com/mozilla/DeepSpeech/releases/tag/v0.7.0) which, unless I'm downloading the wrong thing, looks like a file called "deepspeech-0.8.0-models.tflite" or "deepspeech-0.8.0-models.pbmm". When running the command the quickstart guide recommends,`cargo run --release --example client <path-to-model-dir> <path-to-audio-file>`the process fails with 
```
ERROR: Could not open '/<PATH>/deepspeech-0.8.0-models.tflite/output_graph.pb'.
Error at reading model file '/<PATH>/deepspeech-0.8.0-models.tflite/output_graph.pb
```

(Where `<PATH>` is the path to the file, in my case in a directory on my desktop) 

I'm using deepspeech from commit hash `f94b98d429bdac30b9b9aaa048946537b6ebd575` as the current (as of Aug 10, 2020) project does not compile. (I chalk this up to currently being in migration of a rename from `DeepSpeech` to `STT` and a lot of the variables are not yet renamed to `STT`.)

I see this is due to an api change between the models, where previously (0.6.x) models were in a zipped package. I will see if I can update examples/client.rs working using the new API and submit a PR to fix it - I've not done anything with TF in the past, so not sure how clean my results will be.

### PR DESCRIPTION
**Pull request by NGnius**
I've updated the examples so that they iterate through the contents of the model directory, looking for `.pb` and `.pbmm` file extensions. This is instead of assuming that the model is called `output_graph.pb` (with new releases they're usually called `deepspeech-{version}-models.pbmm` but that's more work to keep up to date), which is not ideal.

Since the examples are now already searching through the whole directory, I added in searching for an external scorer in the model directory as well (`.scorer` extension). The external scorer seems to have better accuracy, so it's a nice-to-have but not strictly necessary.

This also sort of fixes #35 , except this PR is on master and tested against v0.9.0 instead.

Love the project! Thanks for your hard work.

### CODE REVIEW

File: examples/client_simple.rs [hunk 1]
```diff
@@ -27,7 +27,27 @@ fn main() {
...
 		.expect("Please specify an audio file to run STT on");
 	let dir_path = Path::new(&model_dir_str);
-	let mut m = Model::load_from_files(&dir_path.join("output_graph.pb")).unwrap();
+	let mut graph_name: String = String::from("output_graph.pb");
+	let mut scorer_name: Option<String> = None;
+	// search for model in model directory
+	for file in dir_path.read_dir().expect("Specified model dir is not a dir") {
+		if let Ok(f) = file {
+			if f.file_type().unwrap().is_file() {
+				let file_name = f.file_name().into_string().unwrap();
```
Comment (est31) [inline examples/client_simple.rs]: This path to string conversion is not needed. Path has an ends_with function as well.

File: examples/client_extended.rs [hunk 2]
```diff
@@ -36,7 +36,27 @@ fn main() {
...
 		.expect("Please specify an audio file to run STT on");
 	let dir_path = Path::new(&model_dir_str);
-	let mut m = Model::load_from_files(&dir_path.join("output_graph.pb")).unwrap();
+	let mut graph_name: String = String::from("output_graph.pb");
+	let mut scorer_name: Option<String> = None;
+	// search for model in model directory
+	for file in dir_path.read_dir().expect("Specified model dir is not a dir") {
+		if let Ok(f) = file {
+			if f.file_type().unwrap().is_file() {
+				let file_name = f.file_name().into_string().unwrap();
```
Comment (est31) [inline examples/client_extended.rs]: This path to string conversion is not needed. Path has an ends_with function as well.

File: examples/client.rs [hunk 3]
```diff
@@ -29,7 +29,27 @@ fn main() {
...
 		.expect("Please specify an audio file to run STT on");
 	let dir_path = Path::new(&model_dir_str);
-	let mut m = Model::load_from_files(&dir_path.join("output_graph.pb")).unwrap();
+	let mut graph_name: String = String::from("output_graph.pb");
+	let mut scorer_name: Option<String> = None;
+	// search for model in model directory
+	for file in dir_path.read_dir().expect("Specified model dir is not a dir") {
+		if let Ok(f) = file {
+			if f.file_type().unwrap().is_file() {
+				let file_name = f.file_name().into_string().unwrap();
```
Comment (est31) [inline examples/client.rs]: This path to string conversion is not needed. Path has an ends_with function as well.

**Review by est31 — CHANGES_REQUESTED** [review]
Thanks! That's a good catch.

File: examples/client_simple.rs (hunk 1 above)
Comment (NGnius) [reply examples/client_simple.rs]: I completely missed that I could get a PathBuf (woops!). I've changed it to use Path's extension function since that's exactly what I need. (ends_with seems to only work with full Path components, not parts of a filename, so I didn't end up using that)

File: examples/client_extended.rs (hunk 2 above)
Comment (NGnius) [reply examples/client_extended.rs]: I've changed it to use Path's extension function instead.

File: examples/client.rs (hunk 3 above)
Comment (NGnius) [reply examples/client.rs]: I've changed it to use Path's extension function instead.

**Comment by NGnius** [comment]
I've updated my code to use paths as requested. When you have time, please take another look.

I realised I left a bug in my last commit, hence the force push to amend it

**Review by est31 — APPROVED** [review]

**Comment by lissyx** [comment]
@NGnius Sorry for hijacking your old PR, but I'm wondering why you dont handle `tflite` as well ?

**Comment by est31** [comment]
Isn't tflite a library? .so or .dll? Then it's usually loaded at load time of the binary, so any code to look for it would be too late, no?

**Comment by lissyx** [comment]
> Isn't tflite a library? .so or .dll? Then it's usually loaded at load time of the binary, so any code to look for it would be too late, no?

we have two runtimes in two versions of `libdeepspeech.so`, depending on what you pull from, either tensorflow that expects `.pb` or `.pbmm` or the tflite runtime that expects `.tflite` files :)

**Comment by est31** [comment]
Oh I see. PRs welcome!

**Comment by NGnius** [comment]
If I remember correctly, I didn't add `.tflite` support simply because I had no way to test it. I'll create a new PR with support for that file extension as well.
